services:
  frontend:
    container_name: react-frontend-dev
    build:
      context: .
      dockerfile: dev.frontend.Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    environment:
      - REACT_APP_API_URL=http://backend:8080/api

  backend:
    container_name: spring-backend-dev
    build:
      context: ../
      dockerfile: dev.backend.Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/swkom-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  db:
    container_name: postgres-dev
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: swkom-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: